---
title: "Maggie Upjohn Data Exploration"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
```

#1. Reading the datasets:
```{r}
listing <- read_csv("/home/rstudio/courses/2019-20-semester1-stats-316/Project/Kshitij-Rayan-Maggie/listings.csv")
dim(listing) #6716  106
reviews <- read_csv("/home/rstudio/courses/2019-20-semester1-stats-316/Project/Kshitij-Rayan-Maggie/reviews.csv")
dim(reviews) # 142341    
```
#Cleaning variables:
```{r}
#Variables parsing
##Price
listing$price <- as.character(listing$price)
listing$finalprice <- parse_number(listing$price)
##host_response_rate
listing$host_response_rate <- as.character(listing$host_response_rate)
listing$host_response_rate<- with(listing, str_sub( host_response_rate,1,-2))
listing$host_response_rate<-as.integer(listing$host_response_rate)
##security_deposit
listing$security_deposit <- as.character(listing$security_deposit)
listing$security_deposit <- parse_number(listing$security_deposit)
##cleaning_fee and extra people\
listing$cleaning_fee <- as.character(listing$cleaning_fee)
listing$cleaning_fee <- parse_number(listing$cleaning_fee)

```

```{r}
listing %>% ggplot(mapping = aes(x=host_response_rate, y= number_of_reviews_ltm)) +
  geom_point()
```

```{r}
favstats(listing$review_scores_rating)

favstats(listing$host_response_rate)

favstats(listing$finalprice)
favstats(listing$cleaning_fee)
```

```{r}
listing %>%
  ggplot(mapping = aes(x=review_scores_rating, y=number_of_reviews_ltm)) +
  geom_point()
```


```{r}
mean(data.matrix(listing$number_of_reviews_ltm))

listing %>%
count(number_of_reviews_ltm)

listing %>%
  count(price)
```


3306/6716= 0.49 49.22% of the listings had 0 reviews over the past year.  The mean number of reviews for all listings over the past 12 months is 9.864503.

```{r}
p.table <- listing %>%
  group_by(number_of_reviews_ltm) %>%
  summarise (n = n()) %>%
  mutate(freq = n / sum(n))

gmn.model <- glm(number_of_reviews_ltm ~ 1, family = poisson, data = listing)
summary(gmn.model)
lambda <- exp(coef(gmn.model)) 
p.model <- dpois(listing$number_of_reviews_ltm, lambda)   #  modeled pois probabilities
nmes <- mutate(listing, p.model = p.model)

linehist1 <- ggplot(p.table, aes(x = number_of_reviews_ltm, xend = number_of_reviews_ltm, 
                                 y = 0, yend = freq)) +
  geom_segment() + xlim(0, 50) + ylim(0,.15) +
  labs(y = "Proportion", title = "Observed number of reviews")
linehist2 <- ggplot(listing, aes(x = number_of_reviews_ltm, xend = number_of_reviews_ltm, 
                              y = 0, yend = p.model)) +
  geom_segment() + xlim(0, 50) +  ylim(0,.15) +
  labs(y = "Proportion", title = "Poisson modeled number of reviews")
grid.arrange(linehist1, linehist2, ncol=1)
```

```{r}
listing %>%
  count(host_response_rate)


listing %>%
  ggplot(mapping = aes(x=number_of_reviews_ltm, y= host_response_rate)) +
  geom_boxplot()
```

```{r}
listing <- listing %>% mutate(price = gsub("[\\$,]", "", listing$price) %>%
  as.numeric(listing$price))

listing %>% 
  filter(price < 1000)

listing %>% 
  count(room_type)
```
2,344/6716= are under $100

5,573/6716= are under $1000

2776/6716 had l istings with the hosts respond that responded within an hour

4696/6716 listings had the entire home/apartment.

1585/6716 reviewed the listing as 100% rating.
